language: python
cache: pip

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - pypy3

install:
  - pip install -r requirements-dev.txt
  - pip install -U black

script:
  - nosetests --with-coverage --cover-package=slacker_cli
  - flake8 slacker_cli tests
  - black --check --diff .

after_script:
  - coveralls --verbose
